language: php  # 运行语言

os: linux # 测试系统
php:  # 需要测试的php版本
  - 7.2
  - 7.3
  - 7.4

dist: trusty   # 系统版本

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose